language: android
jdk: oraclejdk8

android:
  components:
  - android-21
  - build-tools-21.1.2

script:
 - ./gradlew clean test assemble --stacktrace

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4a9094212020b1f7a094
    on_success: change
    on_failure: change
    on_start: false
