language: android
jdk: oraclejdk7

android:
  components:
  - android-22
  - build-tools-22.0.1

script:
 - ./gradlew clean build assemble artifactoryPublish --stacktrace

notifications:
  email: change