package com.nhaarman.ellie.internal.codegen.repository;

import com.nhaarman.ellie.internal.codegen.column.ColumnInfo;
import com.nhaarman.ellie.internal.codegen.column.ColumnMethodInfo;
import com.nhaarman.ellie.internal.codegen.table.TableInfo;
import com.squareup.javawriter.JavaWriter;

import java.io.IOException;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Locale;

import javax.annotation.processing.Filer;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.VariableElement;
import javax.tools.JavaFileObject;

import static com.nhaarman.ellie.internal.codegen.Modifiers.PRIVATE_FINAL;
import static com.nhaarman.ellie.internal.codegen.Modifiers.PUBLIC;

public class RepositoryWriter {

  private final Filer mFiler;

  private RepositoryInfo mRepositoryInfo;

  private TableInfo mTableInfo;

  private JavaWriter mJavaWriter;

  public RepositoryWriter(final Filer filer) {
    mFiler = filer;
  }

  public void writeRepository(final RepositoryInfo repositoryInfo) throws IOException {
    mRepositoryInfo = repositoryInfo;
    mTableInfo = repositoryInfo.getTableInfo();

    JavaFileObject sourceFile = mFiler.createSourceFile(createRepositoryClassName());
    mJavaWriter = new JavaWriter(sourceFile.openWriter());
    mJavaWriter.setIndent("  ");

    writeHeader();
    writeBeginType();

    writeFields();
    writeConstructor();

    for (ExecutableElement executableElement : mRepositoryInfo.getMethodsToImplement()) {
      implement(executableElement);
    }

    writeReadCursor();

    writeEndType();

    mJavaWriter.close();
  }

  private void writeHeader() throws IOException {
    mJavaWriter.emitSingleLineComment("Generated by Ellie. Do not modify!");
    mJavaWriter.emitPackage(mRepositoryInfo.getPackageName());
  }

  private void writeBeginType() throws IOException {
    String extendingClass = mRepositoryInfo.isInterface() ? null : mRepositoryInfo.getFullyQualifiedName();
    String[] implementingInterface = mRepositoryInfo.isInterface() ? new String[]{mRepositoryInfo.getFullyQualifiedName()} : new String[0];

    mJavaWriter.beginType(createRepositoryClassName(), "class", PUBLIC, extendingClass, implementingInterface);
    mJavaWriter.emitEmptyLine();
  }

  private void writeFields() throws IOException {
    mJavaWriter.emitJavadoc("The {@link %s} that is used for persistence.", "android.database.sqlite.SQLiteDatabase");
    mJavaWriter.emitField("android.database.sqlite.SQLiteDatabase", "mDatabase", PRIVATE_FINAL);
    mJavaWriter.emitEmptyLine();
  }

  private void writeConstructor() throws IOException {
    mJavaWriter.beginConstructor(PUBLIC, "android.database.sqlite.SQLiteDatabase", "database");
    mJavaWriter.emitStatement("mDatabase = database");
    mJavaWriter.endConstructor();
    mJavaWriter.emitEmptyLine();
  }

  private void implement(final ExecutableElement executableElement) throws IOException {
    if (executableElement.getSimpleName().toString().equals("find")) {
      implementFind(executableElement);
    }
  }

  private void implementFind(final ExecutableElement executableElement) throws IOException {
    String[] parameterStrings = {"Long", "id"};

    mJavaWriter.beginMethod(
        executableElement.getReturnType().toString(),
        executableElement.getSimpleName().toString(),
        PUBLIC,
        parameterStrings
    );

    mJavaWriter.beginControlFlow("if (id == null)");
    mJavaWriter.emitStatement("return null");
    mJavaWriter.endControlFlow();
    mJavaWriter.emitEmptyLine();

    mJavaWriter.emitStatement("%s result = null", mTableInfo.getEntityFQN());
    mJavaWriter.emitEmptyLine();

    mJavaWriter.emitStatement(
        "android.database.Cursor cursor = new com.nhaarman.sql_lib.query.Select().from(\"%s\").where(\"id=?\", id).limit(\"1\").fetchFrom(mDatabase)",
        mTableInfo.getTableName()
    );

    mJavaWriter.beginControlFlow("if (cursor.moveToFirst())");
    mJavaWriter.emitStatement("result = read(cursor)");
    mJavaWriter.endControlFlow();
    mJavaWriter.emitStatement("cursor.close()");

    mJavaWriter.emitEmptyLine();
    mJavaWriter.emitStatement("return result");

    mJavaWriter.endMethod();
    mJavaWriter.emitEmptyLine();
  }

  private void writeReadCursor() throws IOException {
    mJavaWriter.beginMethod(mTableInfo.getEntityFQN(), "read", PUBLIC, new String[]{"android.database.Cursor", "cursor"});

    mJavaWriter.emitStatement("%s result = new %s()", mTableInfo.getEntityFQN(), mTableInfo.getEntityFQN());
    mJavaWriter.emitEmptyLine();

    for (ColumnInfo columnInfo : mTableInfo.getColumns()) {
      Collection<ColumnMethodInfo> methodInfos = columnInfo.getMethodInfos();
      for (ColumnMethodInfo methodInfo : methodInfos) {
        if (methodInfo.isSetter()) {
          mJavaWriter.emitStatement(
              "result.%s(cursor.get%s(cursor.getColumnIndex(\"%s\")))", methodInfo.getExecutableElement().getSimpleName(),
              methodInfo.getExecutableElement().getParameters().get(0).asType().toString().substring(
                  methodInfo.getExecutableElement().getParameters().get(0).asType().toString()
                            .lastIndexOf('.') + 1
              ),
              columnInfo.getColumnName()
          );
        }
      }
    }

    mJavaWriter.emitEmptyLine();
    mJavaWriter.emitStatement("return result");


    mJavaWriter.endMethod();
    mJavaWriter.emitEmptyLine();
  }

  private void writeEndType() throws IOException {
    mJavaWriter.endType();
  }


  private String createRepositoryClassName() {
    return String.format("%sRepository", mTableInfo.getTableName().substring(0, 1).toUpperCase(Locale.US) + mTableInfo.getTableName().substring(1));
  }

}
